"""new fields in user model

Revision ID: 183f34a823a2
Revises: 596b8220ac03
Create Date: 2019-09-24 00:44:01.575011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '183f34a823a2'
down_revision = '596b8220ac03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
