"""followers

Revision ID: 525590a483e1
Revises: 183f34a823a2
Create Date: 2019-09-25 00:56:01.864845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '525590a483e1'
down_revision = '183f34a823a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
